version: '3.8'

services:
  ays-valentine-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ays-valentine-lovers-concept
    ports:
      - "5057:5000"
    restart: unless-stopped
    networks:
      - flower-network

networks:
  flower-network:
    driver: bridge
